# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPZJ45SwFAodk35HVQthvW4CiDwjEv8P
"""

def tashxis(belgi):
  if belgi =='Istima':
    return "Parasetamol iching"
  elif belgi == "Bosh og'rig'i":
    return "Bol nol iching"
  elif belgi == "Tish og'rig'i":
    return "Kyupen iching"
  else:
    return "Shifokorga murojaat qiling"
  belgi = input("Kasallik belgisini kiriting:")
  natija = tashxis(belgi)
  print(natija)

import cv2
from google.colab.patches import cv2_imshow  # Import cv2_imshow for Colab

def talaba(ism):
    # Student name and image path mapping
    if ism == "Mubiynaxon":
        student_name = "Abdurahimova"
        img_path = "mubiynaxon_image.jpg"
    elif ism == "Sanamxon":
        student_name = "Rahmonnazarova"
        img_path = "sanamxon_image.jpg"
    elif ism == "Maftuna":
        student_name = "Yigitaliyeva"
        img_path = "maftuna_image.jpg"
    elif ism == "Nodira":
        student_name = "Aliyeva"
        img_path = "nodira_image.jpg"
    else:
        student_name = "Name not found"
        img_path = None

    if img_path:
        img = cv2.imread(img_path)
        if img is not None:
            cv2_imshow(img)
            cv2.waitKey(0)
        else:
            print(f"Error: The image '{img_path}' could not be loaded.")
    else:
        print(f"No image path available for {student_name}.")

    return student_name
ism = input("Talaba ismini kiriting: ")
natija = talaba(ism)
print(natija)